// ============================================================
//  UI — Screen management and glyph exchange interface
// ============================================================

function showScreen(id) {
  document.querySelectorAll('#app > .screen').forEach(el => el.classList.add('hidden'));
  document.getElementById(id).classList.remove('hidden');
}

// --- CHARACTER SELECT ---

function selectCharacter(character) {
  const session = Persist.loadSession() || {};
  session.character = character;
  Persist.saveSession(session);

  // Update UI to show selected
  document.querySelectorAll('.char-option').forEach(el => el.classList.remove('selected'));
  document.getElementById('char-' + character).classList.add('selected');
  document.getElementById('btn-confirm-char').classList.remove('hidden');
}

function confirmCharacter() {
  const session = Persist.loadSession();
  if (!session || !session.character) return;

  // If we already have a shared seed, go straight to game
  if (session.sharedSeed) {
    enterGame();
  } else {
    showSeedExchange();
  }
}

// --- SEED EXCHANGE ---

function showSeedExchange() {
  showScreen('screen-seed');
  const session = Persist.loadSession();

  // Generate our seed if we don't have one
  if (!session.mySeed) {
    session.mySeed = Crypto.generateSeed();
    Persist.saveSession(session);
  }

  document.getElementById('my-seed').textContent = session.mySeed;
  document.getElementById('partner-seed-input').value = '';
  document.getElementById('seed-status').textContent = '';
}

function confirmSeedExchange() {
  const partnerSeed = document.getElementById('partner-seed-input').value.trim().toUpperCase();
  if (partnerSeed.length < 4) {
    document.getElementById('seed-status').textContent = 'Code too short';
    return;
  }

  const session = Persist.loadSession();
  session.partnerSeed = partnerSeed;
  session.sharedSeed = Crypto.combineSeeds(session.mySeed, partnerSeed);
  Persist.saveSession(session);

  document.getElementById('seed-status').textContent = 'Bond established.';
  setTimeout(() => enterGame(), 800);
}

// --- GAME SCREEN ---

function enterGame() {
  const session = Persist.loadSession();
  if (!session) return;

  showScreen('screen-game');

  // Apply timeline theme
  const isKnight = session.character === 'knight';
  document.body.setAttribute('data-timeline', isKnight ? 'past' : 'present');

  const label = isKnight ? 'The Hollow Knight — Past' : 'The Pale Whisper — Present';
  document.getElementById('game-role-label').textContent = label;

  WakeLock.request();
  drawTestScene(session.character);
}

// --- GLYPH EXCHANGE ---

function openGlyphPanel() {
  document.getElementById('glyph-panel').classList.toggle('hidden');
}

function enterGlyph() {
  const input = document.getElementById('glyph-input');
  const code = input.value.trim().toUpperCase();
  if (!code) return;

  const session = Persist.loadSession();
  if (!session || !session.sharedSeed) return;

  // Try to validate against known event IDs
  // For now, just log it (real validation comes with game events)
  const glyphLog = session.glyphLog || [];
  glyphLog.push({
    code,
    time: Date.now(),
    direction: 'received'
  });
  session.glyphLog = glyphLog;
  Persist.saveSession(session);

  addGlyphLogEntry('Received: ' + code, 'received');
  input.value = '';

  // TODO: validate and trigger game events
  addGlyphLogEntry('The glyph resonates...', 'system');
}

function addGlyphLogEntry(text, type) {
  const log = document.getElementById('glyph-log');
  const entry = document.createElement('div');
  entry.className = 'log-entry ' + (type || '');
  entry.textContent = text;
  log.appendChild(entry);
  log.scrollTop = log.scrollHeight;
}

// Show a glyph that was generated by a game event
function showGeneratedGlyph(code, description) {
  const session = Persist.loadSession();
  const glyphLog = session.glyphLog || [];
  glyphLog.push({
    code,
    time: Date.now(),
    direction: 'generated',
    description
  });
  session.glyphLog = glyphLog;
  Persist.saveSession(session);

  // Show in UI
  document.getElementById('glyph-panel').classList.remove('hidden');
  addGlyphLogEntry('A glyph appears: ' + code, 'generated');
  if (description) addGlyphLogEntry(description, 'system');
}

// --- RESET ---

function resetGame() {
  if (confirm('This will erase all progress. Are you sure?')) {
    Persist.clearSession();
    location.reload();
  }
}
